### PR TITLE
Cleanup

### LINKED ISSUE #112: Remove struct on parameter types
Don't remember exactly when it started, but everyone imitated. This is not usefull and actually makes it sometimes harder to catch compilation errors.

### PR DESCRIPTION
**Pull request by riamon-v**
Closes #112

### CODE REVIEW

**Review by Gaspard-- — APPROVED** [review]
I propose remove [[maybe_unused]] while we're at it. PR LGTM.

**Comment by riamon-v** [comment]
Remove [[maybe_unused]] only where necessary right ?

**Comment by Gaspard--** [comment]
Well, the attribute is no longer recognised by gcc, and thus only produces additional warnings. So it's useless everywhere anyway.

**Comment by Gaspard--** [comment]
I think you accidently re-introduced some `struct`s a bit everywhere.

**Pull request merged**
